package com.vadcut.android

enum class TrimErrorCode {
    INVALID_REQUEST,
    INPUT_OPEN_FAILED,
    NO_AUDIO_TRACK,
    UNSUPPORTED_AUDIO_FORMAT,
    MODEL_LOAD_FAILED,
    MODEL_INTEGRITY_FAILED,
    ANALYSIS_FAILED,
    NO_SPEECH_DETECTED,
    EXPORT_FAILED,
    OUTPUT_WRITE_FAILED,
    UNKNOWN,
}
